### ISSUE TITLE
[Q] +compile trick

### ISSUE THREAD

**Issue by nicolas-dufour** [RaphaelMeudec/slurm-hydra-submitit#1]
Hi,
I'm wondering where does the +compile trick come from to have selected multiruns. Cannot find anything in the official hydra doc.

Thanks!

**Comment by RaphaelMeudec** [comment]
Hello,

I guess the paragraph isn't self-explanatory and is a mix-up of several elements. Here are some explanations:

- the main point is that we use the [multirun](https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/) available in hydra
- we use the `${params[*]}` to generate the `"{project_name:P1,train.epochs:30}, {project_name:P2,train.epochs:40}"` string dynamically and avoid a very large command line
- the `+` means we add elements to the configuration as stated in [this page](https://hydra.cc/docs/patterns/configuring_experiments/)
  > Running the experiments from the command line requires prefixing the experiment choice with a +. The experiment config group is an addition, not an override.
- the `+compile` means we add the `${params[*]}` inside a `compile` in the config file. This is where the example is fraudulous: we don't really want to create this `compile` key. It comes from one of my files where I grid-search some learning rates/optimizers passed to a keras `.compile()` method, and I didn't adapt it enough for this repo.

A more suitable example bash file would be the following:

```bash
#!/bin/bash
params=(
    '{model_name:ModelA,epochs:10,batch_size:32},'
    '{model_name:ModelB,epochs:20,batch_size:64}'
)

slurm_hydra_submitit/script.py --multirun hydra/launcher=submitit_slurm train="${params[*]}"
```

Hope this helps!
